### ISSUE TITLE
Documentation improvement - small typo

### ISSUE THREAD

**Issue by wautersj** [Zatikyan/angular-disable-browser-back-button#2]
Not a big issue, but wight be helpful and correcter to fix the small typo in the readme:

<img width="711" alt="Schermafbeelding 2020-04-22 om 15 33 20" src="https://user-images.githubusercontent.com/4070167/79988417-ecc91b00-84ae-11ea-95c7-62a5349db17f.png">

import { BackButtonDisableModule } from 'angular-desable-browser-back-button';
VS
import { BackButtonDisableModule } from 'angular-disable-browser-back-button';

**Comment by Zatikyan** [comment]
Dear @wautersj ,

Thank you for your feedback. I have already fixed that typo issue and published it to npmjs.com as well.
