### ISSUE TITLE
double or multiple clicks doesn't disable back

### ISSUE THREAD

**Issue by Chetna124** [Zatikyan/angular-disable-browser-back-button#3]
Hi,
When you click back two or more times together, it redirects to the previous page.
Facing this bug.

**Comment by Zatikyan** [comment]
Hi @Chetna124 

Thank you for your report, but I can't reproduce the bug. Can you provide more info and can you check is your case related to the [chrome issue about user interactions](https://support.google.com/chrome/thread/8721521?hl=en) ?

**Comment by Zatikyan** [comment]
Hi @Chetna124 

I added a note about the Chrome issue and attached a link to the discussion of chrome issue about user interactions. So I'm closing this issue.

Thank you for your feedback.
