### ISSUE TITLE
support in Angular 16

### ISSUE THREAD

**Issue by anton-po-github** [Zatikyan/angular-disable-browser-back-button#5]
@Zatikyan 

Hi.

thanks for your project, it worked fine in several of my projects before Angular was upgraded to version 16.

at the moment I have updated all my projects to version 16 and I get a number of errors when I try to include the `BackButtonDisableModule` in my project.

will it be possible in the future to have `BackButtonDisableModule` work in Angular 16+ please ?

**Comment by Zatikyan** [comment]
@anton-po-github

Hi Anton. Thanks for letting me know.
Yes, I will update it soon.

**Comment by anton-po-github** [comment]
@Zatikyan 

Thanks a lot.

please let me know when I can return the `BackButtonDisableModule` to my projects, it does a lot of magic for me without any hassle.

**Comment by Zatikyan** [comment]
@anton-po-github 

Hi. I've published v2.0.0 of the module with support for Angular v16. You can install it from [npmjs](https://www.npmjs.com/package/angular-disable-browser-back-button).

Please note, that a newer version of TypeScript is needed for it to work, and `preserveScrollPosition` is replaced with `preserveScroll`.

Enjoy :wink:

**Comment by anton-po-github** [comment]
@Zatikyan 

thanks it works great now.

take care =]
